### ISSUE TITLE
Wikidata dump version replacement

### ISSUE THREAD

**Issue by SRL94** [PhilippChr/CLOCQ#2]
Hi Philipp,

Excellent work! A quick question: could we change the Wikidata dump version? The current version is 2020-04-24 but the ConvQuestions dataset used an older version.

Best regards
Sirui

**Comment by PhilippChr** [comment]
Hi Sirui,

Yes, so if you have the appropriate N-Triples dump, you can follow [this repo](https://github.com/PhilippChr/wikidata-core-for-QA) to transform the dump into the format expected by CLOCQ. But I am not sure you can easily find the N-Triples dump for the same date as the HDT dump used in CONVEX. You could try to export the HDT dump into N-Triples, but overall this might be some overhead.
In CLOCQ, we also used ConvQuestions, and did not observe problems due to the change in the dump. In fact, [CONQUER](https://conquer.mpi-inf.mpg.de) also used a newer dump (same dump from 2020-04-24).

By the way, CLOCQ can now also be accessed via an online API: https://clocq.mpi-inf.mpg.de.
You can play around with the API on the website a bit. You can access Wikidata very conveniently (same dump from 2020-04-24).
We also provide a client to integrate the API into your code easily. The documentation etc will be extended soon.
Any feedback would be appreciated!

Regards,
Philipp
