### ISSUE TITLE
API down & potential reasons

### ISSUE THREAD

**Issue by WuXuan374** [PhilippChr/CLOCQ#6]
Hi, thank you for your great work and wonderful API! It helps me a lot.

The API service seems to be unavailale now, and I think it may have something to do with a recent API request from me: I test  /api/connectivity_check with 2 properties (P127 and some other property).

After that request, the service seems to be unavailable.

I'm really sorry for the trouble brought; if this request is the reason why the service is down, perhaps a parameter check on the interface could help to avoid such cases in the future.

Again, thank you for your great work, and really sorry for the trouble.

**Comment by PhilippChr** [comment]
Hi,

Thanks a lot for the nice words!

I do not think that this caused the problem actually,
since we take care of such cases internally.
But still, thanks for mentioning!

I think it has to do with some internal processes.
The API is restarted for now (will take 2-3 hours until it is available again),
and I will try to further investigate what exactly caused the issue,
to avoid such problems in the future.

Regards,
Philipp

**Comment by WuXuan374** [comment]
Hi,

Thank you for your effort! 
And I will be more careful when using the interfaces.

Danke schön!
